language: csharp
solution: TestAppCalculator/Solution/TestAppCalculator.sln
mono: none
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003131
script:
  - cd TestAppCalculator/Solution/src/Calculator && dotnet restore && dotnet build