language: csharp

env:
 global:
  - EnableNuGetPackageRestore=true 

solution: TestAppCalculator/Solution/TestAppCalculator.sln

dist: trusty
sudo: required

branches:  
  only:
    - master

# os:  
#  - linux
#  - osx

matrix:
  include:
    - os: linux
      mono: none
      dotnet: 1.0.0-preview2-003131
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode8
      mono: latest
      dotnet: none
      env: XAMARIN=1


# before_install:
#  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-
# x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
#  - sudo installer -pkg "MonoFramework-MDK-
# ${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

#install:
  #- if [[ "$DOTNETCORE" == "1" ]]; then nuget restore TestAppCalculator/Solution/TestAppCalculator.sln ; fi
  #- if [[ "$DOTNETCORE" == "1" ]]; then nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner ; fi

script:
  - if [[ "$DOTNETCORE" == "1" ]]; then cd TestAppCalculator/Solution/src/Calculator && dotnet restore && dotnet build -c Release ; fi
  - if [[ "$XAMARIN" == "1" ]]; then cd ../MobileApp/MobileApp.Droid && xbuild /p:Configuration=Release ; fi
#  - cd ../MobileApp.iOS && xbuild /p:Configuration=Release

# deploy:
#   provider: azure_web_apps
#   username:
#   password:
#   site:
#   slot:
